name: Sync multiple branches
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Merge main -> test
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          allow_ff: true
          ff_only: true
          stable_branch: main
          user_name: compliance-github-bot
          development_branch: test
          push_token: 'GITHUB_TOKEN'
        env:
          GITHUB_TOKEN: ${{ github.token }}

#      - name: Set up Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12

      - name: Opening pull request main -> prod
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: main
          TO_BRANCH: prod
