name: Sync multiple branches
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Merge main -> test
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          allow_ff: true
          ff_only: true
          stable_branch: main
          user_name: compliance-github-bot
          development_branch: test
          push_token: 'GITHUB_TOKEN'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Merge main -> prod
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          allow_ff: true
          ff_only: true
          stable_branch: main
          user_name: compliance-github-bot
          development_branch: prod
          push_token: 'GITHUB_TOKEN'
        env:
          GITHUB_TOKEN: ${{ github.token }}
